export default {
  firstName: 'First Name',
  nickname: 'Nickname',
  middleName: 'Middle Name',
  maidenName: 'Maiden Name',
  lastName: 'Last Name',
  suffix: 'Suffix',
  gender: 'M/F',
  phoneNumber: 'Phone Number',
  email: 'Email Address',
  birthday: 'Birthday',
  street1: 'Home Address',
  street2: 'Home Address 2',
  city: 'City',
  state: 'State',
  zip: 'Zip Code',
  dod: 'Date of Death',
  spouse: 'Spouse',
  parents: 'Parents',
  children: 'Children'
}
