// Contacts
export const ADD_CONTACT = 'ADD_CONTACT'
export const DEACTIVATE_CONTACT = 'DEACTIVATE_CONTACT'
export const REMOVE_CONTACT = 'REMOVE_CONTACT'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const UPLOAD_CONTACTS = 'UPLOAD_CONTACTS'
export const MERGE_CONTACTS = 'MERGE_CONTACTS'

// Current Contact
export const UPDATE_CURRENT_CONTACT = 'UPDATE_CURRENT_CONTACT'
export const RESET_CURRENT_CONTACT = 'RESET_CURRENT_CONTACT'
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT'

// Families
export const ADD_FAMILY = 'ADD_FAMILY'
export const DEACTIVATE_FAMILY = 'DEACTIVATE_FAMILY'
export const REMOVE_FAMILY = 'REMOVE_FAMILY'
export const UPDATE_FAMILY = 'UPDATE_FAMILY'

// Addresses
export const ADD_ADDRESS = 'ADD_ADDRESS'
export const DEACTIVATE_ADDRESS = 'DEACTIVATE_ADDRESS'
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'

// Users
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
